using System.Management;
using System.Net.NetworkInformation;
using System.Text;

namespace FieldKit;

public class SystemInfoForm : Form
{
    private readonly RichTextBox _textBox;
    private readonly Button _exportButton;
    private readonly Button _closeButton;
    private readonly string _report;

    public SystemInfoForm()
    {
        Text = "System Information — FieldKit";
        Size = new Size(680, 600);
        MinimumSize = new Size(500, 400);
        StartPosition = FormStartPosition.CenterParent;
        Font = new Font("Segoe UI", 9.5f);
        BackColor = Color.White;
        ShowInTaskbar = false;

        var monoFont = IsFontInstalled("Cascadia Mono")
            ? new Font("Cascadia Mono", 9f)
            : new Font("Consolas", 9f);

        _report = BuildReport();

        _textBox = new RichTextBox
        {
            Dock = DockStyle.Fill,
            ReadOnly = true,
            BorderStyle = BorderStyle.None,
            BackColor = Color.White,
            ForeColor = Color.FromArgb(40, 40, 40),
            Font = monoFont,
            WordWrap = false,
            Text = _report
        };

        var buttonPanel = new FlowLayoutPanel
        {
            Dock = DockStyle.Bottom,
            Height = 44,
            FlowDirection = FlowDirection.RightToLeft,
            Padding = new Padding(8, 6, 8, 6),
            BackColor = Color.FromArgb(248, 248, 248)
        };

        _closeButton = new Button
        {
            Text = "Close",
            Width = 80, Height = 30,
            Margin = new Padding(0, 0, 4, 0)
        };
        _closeButton.Click += (_, _) => Close();

        _exportButton = new Button
        {
            Text = "Export to File",
            Width = 110, Height = 30,
            BackColor = Color.FromArgb(0, 120, 215),
            ForeColor = Color.White,
            FlatStyle = FlatStyle.Flat,
            Margin = new Padding(0, 0, 4, 0)
        };
        _exportButton.FlatAppearance.BorderSize = 0;
        _exportButton.Click += OnExportClick;

        buttonPanel.Controls.AddRange([_closeButton, _exportButton]);

        Controls.Add(_textBox);
        Controls.Add(buttonPanel);

        // Color the section headers after text is set
        ColorHeaders();
    }

    private void ColorHeaders()
    {
        var headerColor = Color.FromArgb(0, 100, 180);
        var lines = _textBox.Lines;
        int pos = 0;
        for (int i = 0; i < lines.Length; i++)
        {
            if (lines[i].StartsWith("===") || lines[i].StartsWith("---"))
            {
                // Color the previous line as a header
                if (i > 0)
                {
                    int prevStart = pos - lines[i - 1].Length - 1;
                    if (prevStart >= 0)
                    {
                        _textBox.Select(prevStart, lines[i - 1].Length);
                        _textBox.SelectionColor = headerColor;
                        _textBox.SelectionFont = new Font(_textBox.Font, FontStyle.Bold);
                    }
                }
            }
            pos += lines[i].Length + 1; // +1 for newline
        }
        _textBox.Select(0, 0);
    }

    private void OnExportClick(object? sender, EventArgs e)
    {
        using var dlg = new SaveFileDialog
        {
            FileName = $"SystemInfo_{Environment.MachineName}_{DateTime.Now:yyyyMMdd}.txt",
            Filter = "Text files (*.txt)|*.txt|All files (*.*)|*.*",
            DefaultExt = "txt"
        };

        if (dlg.ShowDialog(this) == DialogResult.OK)
        {
            try
            {
                File.WriteAllText(dlg.FileName, _report, Encoding.UTF8);
                MessageBox.Show($"Saved to {dlg.FileName}", "Export Complete",
                    MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Export failed: {ex.Message}", "Error",
                    MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }
    }

    private static string BuildReport()
    {
        var sb = new StringBuilder();

        sb.AppendLine($"System Information Report — {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine("Generated by FieldKit v1.0");
        sb.AppendLine(new string('=', 60));
        sb.AppendLine();

        // --- Computer ---
        sb.AppendLine("COMPUTER");
        sb.AppendLine(new string('-', 60));
        sb.AppendLine($"  Name:          {Environment.MachineName}");
        sb.AppendLine($"  User:          {Environment.UserDomainName}\\{Environment.UserName}");
        sb.AppendLine($"  Uptime:        {FormatUptime()}");
        sb.AppendLine();

        // --- OS ---
        sb.AppendLine("OPERATING SYSTEM");
        sb.AppendLine(new string('-', 60));
        AppendWmi(sb, "Win32_OperatingSystem", obj =>
        {
            sb.AppendLine($"  OS:            {obj["Caption"]}");
            sb.AppendLine($"  Version:       {obj["Version"]}  (Build {obj["BuildNumber"]})");
            sb.AppendLine($"  Architecture:  {obj["OSArchitecture"]}");
            sb.AppendLine($"  Install date:  {FormatWmiDate(obj["InstallDate"]?.ToString())}");
        });
        sb.AppendLine();

        // --- CPU ---
        sb.AppendLine("PROCESSOR");
        sb.AppendLine(new string('-', 60));
        AppendWmi(sb, "Win32_Processor", obj =>
        {
            sb.AppendLine($"  Name:          {obj["Name"]?.ToString()?.Trim()}");
            sb.AppendLine($"  Cores:         {obj["NumberOfCores"]} cores, {obj["NumberOfLogicalProcessors"]} threads");
            sb.AppendLine($"  Max speed:     {obj["MaxClockSpeed"]} MHz");
        });
        sb.AppendLine();

        // --- Memory ---
        sb.AppendLine("MEMORY");
        sb.AppendLine(new string('-', 60));
        AppendWmi(sb, "Win32_ComputerSystem", obj =>
        {
            var totalBytes = Convert.ToDouble(obj["TotalPhysicalMemory"]);
            sb.AppendLine($"  Total:         {totalBytes / (1024 * 1024 * 1024):F1} GB");
        });
        try
        {
            using var searcher = new ManagementObjectSearcher("SELECT Capacity, Speed, Manufacturer FROM Win32_PhysicalMemory");
            int slot = 0;
            foreach (ManagementObject obj in searcher.Get())
            {
                using (obj)
                {
                    slot++;
                    var cap = Convert.ToDouble(obj["Capacity"]) / (1024 * 1024 * 1024);
                    var speed = obj["Speed"];
                    var mfr = obj["Manufacturer"]?.ToString()?.Trim();
                    sb.AppendLine($"  Slot {slot}:        {cap:F0} GB{(speed != null ? $"  {speed} MHz" : "")}{(string.IsNullOrEmpty(mfr) ? "" : $"  ({mfr})")}");
                }
            }
        }
        catch { }
        sb.AppendLine();

        // --- BIOS ---
        sb.AppendLine("BIOS / MOTHERBOARD");
        sb.AppendLine(new string('-', 60));
        AppendWmi(sb, "Win32_BIOS", obj =>
        {
            sb.AppendLine($"  Manufacturer:  {obj["Manufacturer"]}");
            sb.AppendLine($"  Version:       {obj["SMBIOSBIOSVersion"]}");
            sb.AppendLine($"  Serial:        {obj["SerialNumber"]}");
        });
        AppendWmi(sb, "Win32_BaseBoard", obj =>
        {
            sb.AppendLine($"  Board:         {obj["Manufacturer"]} {obj["Product"]}");
        });
        sb.AppendLine();

        // --- GPU ---
        sb.AppendLine("GRAPHICS");
        sb.AppendLine(new string('-', 60));
        try
        {
            using var searcher = new ManagementObjectSearcher("SELECT Name, DriverVersion, AdapterRAM FROM Win32_VideoController");
            foreach (ManagementObject obj in searcher.Get())
            {
                using (obj)
                {
                    var ram = Convert.ToDouble(obj["AdapterRAM"] ?? 0);
                    var ramText = ram > 0 ? $"  ({ram / (1024 * 1024 * 1024):F0} GB)" : "";
                    sb.AppendLine($"  {obj["Name"]}{ramText}");
                    sb.AppendLine($"    Driver:      {obj["DriverVersion"]}");
                }
            }
        }
        catch { sb.AppendLine("  Unable to query"); }
        sb.AppendLine();

        // --- Disks ---
        sb.AppendLine("STORAGE");
        sb.AppendLine(new string('-', 60));
        try
        {
            var drives = DriveInfo.GetDrives().Where(d => d.IsReady && d.DriveType == DriveType.Fixed);
            foreach (var d in drives)
            {
                var total = d.TotalSize / (1024.0 * 1024 * 1024);
                var free = d.AvailableFreeSpace / (1024.0 * 1024 * 1024);
                var pct = (1 - free / total) * 100;
                sb.AppendLine($"  {d.Name,-4} {d.DriveFormat,-6}  {total:F0} GB total,  {free:F1} GB free  ({pct:F0}% used)");
            }
        }
        catch { sb.AppendLine("  Unable to query"); }
        // Physical disk info (SSD vs HDD)
        try
        {
            using var searcher = new ManagementObjectSearcher("SELECT Model, MediaType, Size FROM Win32_DiskDrive");
            foreach (ManagementObject obj in searcher.Get())
            {
                using (obj)
                {
                    var size = Convert.ToDouble(obj["Size"] ?? 0) / (1024.0 * 1024 * 1024);
                    var mediaType = obj["MediaType"]?.ToString() ?? "";
                    sb.AppendLine($"  {obj["Model"]}  ({size:F0} GB, {mediaType})");
                }
            }
        }
        catch { }
        sb.AppendLine();

        // --- Network ---
        sb.AppendLine("NETWORK");
        sb.AppendLine(new string('-', 60));
        try
        {
            var adapters = NetworkInterface.GetAllNetworkInterfaces()
                .Where(n => n.OperationalStatus == OperationalStatus.Up
                         && n.NetworkInterfaceType != NetworkInterfaceType.Loopback);
            foreach (var adapter in adapters)
            {
                sb.AppendLine($"  {adapter.Name}  ({adapter.NetworkInterfaceType})");
                sb.AppendLine($"    MAC:         {adapter.GetPhysicalAddress()}");
                var ips = adapter.GetIPProperties().UnicastAddresses;
                foreach (var ip in ips)
                {
                    if (ip.Address.AddressFamily == System.Net.Sockets.AddressFamily.InterNetwork)
                        sb.AppendLine($"    IPv4:        {ip.Address}");
                    else if (ip.Address.AddressFamily == System.Net.Sockets.AddressFamily.InterNetworkV6
                             && !ip.Address.IsIPv6LinkLocal)
                        sb.AppendLine($"    IPv6:        {ip.Address}");
                }
            }
        }
        catch { sb.AppendLine("  Unable to query"); }
        sb.AppendLine();

        // --- Windows Update ---
        sb.AppendLine("RECENT WINDOWS UPDATES");
        sb.AppendLine(new string('-', 60));
        try
        {
            using var searcher = new ManagementObjectSearcher("SELECT HotFixID, InstalledOn, Description FROM Win32_QuickFixEngineering");
            var patches = new List<(string Id, DateTime Date, string Desc)>();
            foreach (ManagementObject obj in searcher.Get())
            {
                using (obj)
                {
                    var id = obj["HotFixID"]?.ToString() ?? "";
                    var desc = obj["Description"]?.ToString() ?? "";
                    if (obj["InstalledOn"] is string s && DateTime.TryParse(s, out var dt))
                        patches.Add((id, dt, desc));
                }
            }
            foreach (var p in patches.OrderByDescending(p => p.Date).Take(10))
                sb.AppendLine($"  {p.Date:yyyy-MM-dd}  {p.Id,-12}  {p.Desc}");
            if (patches.Count > 10)
                sb.AppendLine($"  ... and {patches.Count - 10} more");
        }
        catch { sb.AppendLine("  Unable to query"); }
        sb.AppendLine();

        // --- About ---
        sb.AppendLine(new string('=', 60));
        sb.AppendLine("FieldKit v1.0");
        sb.AppendLine("Created by Keith S. Crawford (@tsudo)");
        sb.AppendLine("Licensed under the MIT License");
        sb.AppendLine("Not affiliated with Microsoft Corporation.");
        sb.AppendLine("https://github.com/tsudo/fieldkit");

        return sb.ToString();
    }

    private static void AppendWmi(StringBuilder sb, string className, Action<ManagementObject> handler)
    {
        try
        {
            using var searcher = new ManagementObjectSearcher($"SELECT * FROM {className}");
            foreach (ManagementObject obj in searcher.Get())
            {
                using (obj) { handler(obj); }
            }
        }
        catch { sb.AppendLine("  Unable to query"); }
    }

    private static string FormatUptime()
    {
        var uptime = TimeSpan.FromMilliseconds(Environment.TickCount64);
        var boot = DateTime.Now - uptime;
        if (uptime.TotalDays >= 1)
            return $"{(int)uptime.TotalDays}d {uptime.Hours}h (since {boot:MMM d, HH:mm})";
        return $"{uptime.Hours}h {uptime.Minutes}m (since {boot:HH:mm})";
    }

    private static string FormatWmiDate(string? wmiDate)
    {
        if (wmiDate == null) return "Unknown";
        try
        {
            var dt = ManagementDateTimeConverter.ToDateTime(wmiDate);
            return dt.ToString("yyyy-MM-dd");
        }
        catch { return wmiDate; }
    }

    private static bool IsFontInstalled(string fontName)
    {
        using var testFont = new Font(fontName, 9f);
        return testFont.Name.Equals(fontName, StringComparison.OrdinalIgnoreCase);
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
            _textBox.Font.Dispose();
        base.Dispose(disposing);
    }
}
